# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassPass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClassPass

pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'ClassPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClassPassUITests' do
    # Pods for testing
  end

end
